name: frontend
description: Meditação

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.1.0
  cupertino_icons: ^1.0.2
  sentry: ^6.5.1
  http: ^0.13.4
  provider: ^6.0.3
  stacked: ^2.3.12
  stacked_services:
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Bold.ttf
        - asset: assets/fonts/Comfortaa-Light.ttf
        - asset: assets/fonts/Comfortaa-Regular.ttf
    - family: ModernSans
      fonts:
        - asset: assets/fonts/ModernSans-Light.otf
          weight: 700
  uses-material-design: true

#   assets:
#     - fonts/Comfortaa-Bold.ttf
#     - fonts/Comfortaa-Light.ttf
#     - fonts/Comfortaa-Regular.ttf
#     - fonts/ModernSans-Light.otf
